#version: '3.7'

#services:
#  nginx1_container:
#    container_name: nginx1_container
#    image: nginx:latest
#    ports:
#      - 8888:80
web:
    image: nginx:latest
    ports:
        - "8888:80"
    volumes:
        - ./code:/code
        - ./www/project1/site.conf:/etc/nginx/conf.d/site.conf
        - ./logs:/var/log/nginx
        #- ./site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
php:
    image: php:7-fpm
    volumes:
        - ./code:/code
        #- ./www/project1/site.conf:/etc/nginx/conf.d/site.conf